name: Auto-release

on:
  workflow_dispatch: {}
  schedule:
    - cron: '10 3 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Determine if a new release is required
        id: release-check
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          # See https://stackoverflow.com/a/8653732
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          changes=$(git diff "v${CURRENT_VERSION}"..@)
          if [[ -n "$changes" ]]; then
            echo "::set-output name=newTag::${NEW_VERSION}"
            echo "::set-output name=releaseRequired::true"
          else
            echo "::set-output name=releaseRequired::false"
          fi

      - name: Create new tag & push
        if: ${{ steps.release-check.outputs.releaseRequired == 'true' }}
        env:
          NEW_VERSION: ${{ steps.release-check.outputs.newTag }}
        run: |
          jq '.version = "'${NEW_VERSION}'"' package.json > package.json.tmp && mv package.json.tmp package.json

          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add .
          git commit -m "Release version ${NEW_VERSION}"
          git tag -a -m "Release version ${NEW_VERSION}" "v${NEW_VERSION}"
          git push --follow-tags
